version: '2'
services:
  php:
    build: .
    command: ["/var/www/bin/wait-for-it", "-t", "60", "mysql:3306", "--", "/var/www/bin/install"]
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - ./html:/var/www/html

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: www
      MYSQL_ROOT_PASSWORD: root
