version: '2'
services:
  php:
    build: .
    command: -- ./install.sh
    ports:
      - "80:80"
    depends_on:
      - mysql
    entrypoint: ./wait-for-it.sh mysql:3306
    volumes:
      - .:/var/www/html/wordpress-4.6.1/woocommerce-2.6.6

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: www
      MYSQL_ROOT_PASSWORD: root